### ISSUE TITLE
Error scraping strikes and takedowns counts

### ISSUE THREAD

**Issue by reecelui** [FritzCapuyan/ufc-api#1]
**Describe the issue:**
when using the get_fighter() function, searching for a fighter returns an IndexError, this does not occur for all fighters only some. This is most likely a small change in the scraped websites page structure.

**Expected outcome:**
should return strikes and takedowns json.

**Actual outcome**
returns indexError: list index out of range

**How to reproduce error:**
`get_fighter('Alex Pereira')`

**Temporary Solution:**
_note: this solution wont return the strike and takedown count for affected fighters but solves the IndexError_

Add a try except statement to the get_ufc_stats() function:
`try:
        fighter = {
            'strikes': {
                'attempted': str_tds[1],
                'landed': str_tds[0],
                'standing': distance[0].split(" ")[0],
                'clinch': distance[1].split(" ")[0],
                'ground': distance[2].split(" ")[0],
                'striking defense': stats[4].strip(),
                'strikes per minute': stats[0].strip()
            },
            'takedowns': {
                'attempted': str_tds[3],
                'landed': str_tds[2],
                'takedown defense':stats[5].strip(),
                'subs per 15min': stats[3].strip()
            }
        }
    except:
        fighter = {
            'strikes': {},
            'takedowns': {}
        }`

**Additional Notes:**
Thanks for building this web crawler, it's by far the best UFC crawler i've used to date. Hopefully this issue is seen, and fixed. If it isn't fixed in the near future and I have time I will look at fixing the issue myself.

**Comment by FritzCapuyan** [comment]
Thanks for bringing this to my attention! To be honest I didn't think anyone actually used this crawler haha. Looks like the issue was for fighters with 0 of any stats. i.e. Alex Pereira has never landed a takedown in the UFC, and instead of showing a 0 on their website, the UFC leaves it blank. Then, when lxml is looking for text, it sees no text in that element and skips it, leaving a list with just 3 elements: [strikes landed, strikes attempted, takedowns attempted]. I've added some logic to look through the html elements and if there is no text, append a zero to the list. This should be working now. 
Unrelated, but I also host a much faster and more scalable api on https://rapidapi.com/ZackYoung/api/complete-mma-api. It's not totally free, but it's much faster because it's based on a database with UFC (and MMA generally) data that I host, so doesn't rely on making a google search and multiple requests for each fighter.
